[GLOBAL]
pants_version = "2.4.1"
pantsd = true
backend_packages = ["pants.backend.python"]
build_file_prelude_globs = ["pants-plugins/macros.py"]

[source]
root_patterns = ['/src/*','/pants-plugins']

[python-setup]
interpreter_constraints = ["CPython>=3.8"]
